[2024-05-14T21:15:55.503+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-14T21:15:52.911196+00:00 [queued]>
[2024-05-14T21:15:55.531+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-14T21:15:52.911196+00:00 [queued]>
[2024-05-14T21:15:55.532+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-05-14T21:15:55.557+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): transform_data_task> on 2024-05-14 21:15:52.911196+00:00
[2024-05-14T21:15:55.576+0000] {standard_task_runner.py:60} INFO - Started process 395 to run task
[2024-05-14T21:15:55.576+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ademe_transform_data', 'transform_data_task', 'manual__2024-05-14T21:15:52.911196+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/tansform_data.py', '--cfg-path', '/tmp/tmpnmrp4nng']
[2024-05-14T21:15:55.578+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask transform_data_task
[2024-05-14T21:15:55.658+0000] {task_command.py:423} INFO - Running <TaskInstance: ademe_transform_data.transform_data_task manual__2024-05-14T21:15:52.911196+00:00 [running]> on host 0f2797502ce2
[2024-05-14T21:15:55.767+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ademe_transform_data' AIRFLOW_CTX_TASK_ID='transform_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T21:15:52.911196+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T21:15:52.911196+00:00'
[2024-05-14T21:15:55.856+0000] {logging_mixin.py:188} INFO -            n_dpe                                            payload
0  2185N0146647X  {"conso_chauffage_depensier_e_finale": "917.6"...
1  2144N0042508Z  {"conso_chauffage_depensier_e_finale": "1651.8...
2  2156N0269293Y  {"conso_chauffage_depensier_e_finale": "1280.2...
3  2150N0042791C  {"conso_chauffage_depensier_e_finale": "2060.2...
4  2138N0565214V  {"conso_chauffage_depensier_e_finale": "2042.5...
[2024-05-14T21:15:55.861+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tansform_data.py", line 37, in transform
    for _, row in df_existing.iterrows():
NameError: name 'df_existing' is not defined
[2024-05-14T21:15:55.871+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=ademe_transform_data, task_id=transform_data_task, execution_date=20240514T211552, start_date=20240514T211555, end_date=20240514T211555
[2024-05-14T21:15:55.888+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task transform_data_task (name 'df_existing' is not defined; 395)
[2024-05-14T21:15:55.921+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-14T21:15:55.960+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
